// Autogenerated from backend (run main of org.sailcbi.APIServer.Entities.access.CbiPermissions)
export const Permissions = {
	PERM_CAN_GRANT_ADHOC: 2,
	PERM_RESET_PASSWORD: 1,
	PERM_GENERAL_ADMIN: 1024,
}