// Autogenerated from backend (run main of org.sailcbi.APIServer.Entities.access.CbiAccessUtil)
export const PERMISSIONS = { 
	PERM_CAN_GRANT_ADHOC: 2,
	PERM_RESET_PASSWORD: 1,
	PERM_UPDATE_DOCK_REPORT_RESTRICTED: 1026,
	PERM_SIGN_DOCK_REPORT: 1025,
	PERM_GENERAL_ADMIN: 1024,
};
export const ROLES = [ 
	{ id: 512, name: 'General Admin', description: 'Access to misc management screens/functionality' },
	{ id: 513, name: 'Dockmaster', description: 'Dockmaster' },
];
export const ACCESS_PROFILES = [ 
	{ id: 64, name: 'System Admin' },
	{ id: 65, name: 'Global Admin' },
	{ id: 66, name: 'JP Director' },
	{ id: 67, name: 'AP Director' },
	{ id: 68, name: 'FO Manager' },
	{ id: 69, name: 'FO Supervisor' },
	{ id: 70, name: 'FO Staff' },
	{ id: 71, name: 'Dockmaster' },
	{ id: 72, name: 'Dockstaff' },
	{ id: 73, name: 'Accountant' },
	{ id: 74, name: 'JP Instructor' },
	{ id: 75, name: 'Guest' },
];